= GitHub Actions Deployment
Arwed Schnalzenberger
1.0.0, {docdate}
:imagesdir: img
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
// :toc:
// :toclevels: 1
:experimental:
//https://gist.GitHub.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74?permalink_comment_id=3948218
ifdef::env-GitHub[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Übersicht

Dieses Projekt wurde im Rahmen einer Präsentation über GitHub Actions entwickelt und enthält drei von mir erstellte GitHub Action-Skripte sowie Erläuterungen zu deren Funktionsweise und Einsatz.

=== Enthaltene Skripte

* Build
** Dieses Skript erstellt ein Docker-Image aus einem kleinen Maven-Java-Projekt und pusht das fertige Image in die Container Registry "ghcr.io".
* Deploy
** Hier wird das zuvor erstellte Image in einer Kubernetes-Umgebung aktualisiert. Die Bereitstellung erfolgt mittels `kubectl` und einer in den GitHub Secrets gespeicherten `kubectl`-Konfigurationsdatei.
* Release Artifacts
** Dieses Skript erstellt ein Prerelease auf GitHub. Dabei werden alle Commits seit dem letzten Release zusammengefasst und mit den Commit-Nachrichten sowie dem `.jar`-Artefakt der Maven-Java-Anwendung veröffentlicht.

=== Weitere Dokumentation

Die vollständige Dokumentation zu diesem Projekt ist auf GitHub Pages verfügbar:
https://2425-5bhif-wmc.github.io/01-referate-HikariTempest/



