@host = http://localhost:8080/
//@host = https://if200112.cloud.htl-leonding.ac.at/


### GET vehicles
GET {{host}}/vehicle
Accept: application/json

### GET vehicle by license plate
GET {{host}}/vehicle/123
Accept: application/json

### Send POST request with vehicle json body
POST {{host}}/vehicle
Content-Type: application/json

{
  "licensePlate": "123",
  "model": "nissan",
  "color": "blue",
  "year": 2015
}

### Send PUT request with vehicle json body
PUT {{host}}/vehicle
Content-Type: application/json

{
  "licensePlate": "123",
  "model": "Nissan",
  "color": "red",
  "year": 2015
}

### Send Delete request with vehicle json body
DELETE {{host}}/vehicle
Content-Type: application/json

{
  "licensePlate": "123",
  "model": "Nissan",
  "color": "red",
  "year": 2015
}

